version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV="development"  # Default environment
    command: ["python", "run.py", "--env", "development"]  # Pass the environment dynamically
    depends_on:
      - db
    networks:
      - mynetwork

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chargeHub
    networks:
      - mynetwork
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:

networks:
  mynetwork:
